Repository horntail0/SSDProject, pull requests merged in 2024-04, with the labels that each got.

#14 Feature/ssdwrite
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD_TC/test.cpp
Labels: Feat

#17 Test: add test for ssd read
  SSDProject/SSD/File.cpp
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD_TC/test.cpp
Labels: Feat, Test

#27 Feature/ssdwrite
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD_TC/test.cpp
Labels: Feat

#26 Feat : main 루프 코드 작성
  SSDProject/Shell/main.cpp
  SSDProject/Shell/shell.cpp
Labels: Feat

#28 Test : TestApp1 스크립트 코드 작성
  SSDProject/Shell/shell.cpp
  SSDProject/Shell_TC/test.cpp
Labels: Test

#29 [Test][Green] Input argument validity check 구현
  SSDProject/Shell/shell.cpp
  SSDProject/Shell_TC/test.cpp
Labels: Feat, Test

#35 [feat] implement file write function
  SSDProject/SSD/File.cpp
  SSDProject/SSD_TC/test.cpp
Labels: Feat, Test

#37 [feat] implement SSD argument handling
  SSDProject/SSD/main.cpp
Labels: Feat

#40 Feature/cmdwrite
  SSDProject/SSD/main.cpp
Labels: Feat

#43 Refactor: modify writeFileTotal
  SSDProject/SSD/File.cpp
Labels: Refactor

#42 [feat] ssd.exe invalid argc handling
  SSDProject/SSD/main.cpp
Labels: Feat

#44 [Test] INVALID COMMAND 출력 TC 작성 및 구현
  SSDProject/Shell/shell.cpp
  SSDProject/Shell_TC/test.cpp
Labels: Test

#39 Style: Coding Standard 맞지 않은 코드들 수정 및 Editorconfig 추가
  SSDProject/.editorconfig
  SSDProject/SSD/File.cpp
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD_TC/test.cpp
  SSDProject/Shell/SSDInterface.cpp
  SSDProject/Shell/shell.cpp
  SSDProject/Shell_TC/test.cpp
Labels: Style

#48 [refactor] nand.txt filename to macro
  SSDProject/SSD/File.cpp
Labels: Refactor

#47 [Style] Coding Standard formatting
  SSDProject/Shell/SSDAdapter.cpp
  SSDProject/Shell/shell.cpp
  SSDProject/Shell_TC/test.cpp
Labels: Style

#50 [test] add test for ssd write command
  SSDProject/SSD_TC/test.cpp
Labels: Feat, Test

#51 [Style] Coding style 적용
  SSDProject/Shell/shell.cpp
Labels: Style

#66 Feature/ssdwritetest
  SSDProject/SSD_TC/test.cpp
Labels: Feat, Test

#67 Feat : TestApp1, TestApp2 코드 작성
  SSDProject/Shell/main.cpp
Labels: Feat

#69 [Test] add test for ssd read
  SSDProject/SSD/File.cpp
  SSDProject/SSD_TC/test.cpp
Labels: Test

#70 refactoring: SSD write의 invalid argument check를 작은 function으로 분리했습니다
  SSDProject/SSD/SSD.cpp
Labels: Refactor

#73 test: update TC for SSD writing with invalid argument
  SSDProject/SSD_TC/test.cpp
Labels: fix, Test

#76 [Feat] modify read test
  SSDProject/SSD/File.cpp
  SSDProject/SSD_TC/test.cpp
Labels: Feat, Test

#77 [refactor] modify write method
  SSDProject/SSD/File.cpp
Labels: Refactor

#81 [feat] add erase method
  SSDProject/SSD/File.cpp
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD_TC/test.cpp
Labels: Feat, Test

#80 feat: add E command in main
  SSDProject/SSD/main.cpp
Labels: Feat

#82 Feat: Shell 에서 Erase 구현
  SSDProject/Shell/SSDAdapter.cpp
  SSDProject/Shell/SSDAdapter.h
  SSDProject/Shell/SSDInterface.h
  SSDProject/Shell/main.cpp
  SSDProject/Shell/shell.cpp
  SSDProject/Shell/shell.h
  SSDProject/Shell_TC/test.cpp
Labels: Feat

#85 feat: add method for buffered operation and flush
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD/main.cpp
Labels: Feat

#84 Feature/shellerase
  SSDProject/Shell/shell.cpp
  SSDProject/Shell/shell.h
Labels: fix, Refactor

#92 [feat] implement buffer write with flush
  SSDProject/SSD/File.cpp
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD_TC/test.cpp
Labels: Feat, Test

#93 [Feat] add fastbuffer
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD_TC/test.cpp
  SSDProject/Shell_TC/test.cpp
Labels: Feat

#95 Refactor : Runner 클래스 리팩토링
  SSDProject/Shell/Runner.cpp
  SSDProject/Shell/Runner.h
  SSDProject/Shell/main.cpp
Labels: Refactor

#96 Refactor: Singleton 패턴 추가
  SSDProject/Shell/Runner.cpp
  SSDProject/Shell/Runner.h
  SSDProject/Shell/SSDAdapter.cpp
  SSDProject/Shell/SSDAdapter.h
  SSDProject/Shell/SSDInterface.h
  SSDProject/Shell/main.cpp
  SSDProject/Shell/shell.cpp
  SSDProject/Shell/shell.h
  SSDProject/Shell_TC/test.cpp
Labels: Refactor

#98 Fix : Merge Resolve 도중 잘못 병합한 부분 수정
  SSDProject/Shell/Runner.cpp
Labels: fix

#100 [feat] add TC for buffer write, erase
  SSDProject/SSD_TC/test.cpp
Labels: Feat, Test

#103 Feature/rebuild
  SSDProject/Shell/LoopWriteAndReadCompare.cpp
  SSDProject/Shell/LoopWriteAndReadCompare.h
  SSDProject/Shell/Runner.cpp
  SSDProject/Shell/Shell.vcxproj
  SSDProject/Shell/Shell.vcxproj.filters
  SSDProject/Shell/ShellLogger.cpp
  SSDProject/Shell/ShellLogger.h
  SSDProject/Shell/ShellTestBuilder.cpp
  SSDProject/Shell/ShellTestBuilder.h
  SSDProject/Shell/TestCase.h
  SSDProject/Shell/main.cpp
  SSDProject/Shell/shell.cpp
  SSDProject/Shell/shell.h
  SSDProject/Shell/testapp1.cpp
  SSDProject/Shell/testapp1.h
  SSDProject/Shell/testapp2.cpp
  SSDProject/Shell/testapp2.h
  SSDProject/Shell/write10andcompare.cpp
  SSDProject/Shell/write10andcompare.h
  SSDProject/Shell_TC/test.cpp
Labels: Feat

#104 [refactor] refactor read file
  SSDProject/SSD/File.cpp
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD_TC/test.cpp
  SSDProject/Shell_TC/test.cpp
Labels: Refactor

#105 fix: check if file exists before delete
  SSDProject/SSD_TC/SSD_TC.vcxproj
  SSDProject/SSD_TC/test.cpp
Labels: fix, Test

#106 [refactor] refactor fast write
  SSDProject/SSD/SSD.cpp
Labels: Refactor

#108 Fix : 함수 오버로딩으로 TC 몇개 빌드오류 나는 것 해결
  SSDProject/.gitignore
  SSDProject/Shell_TC/test.cpp
Labels: fix

#109 [refactoring] SSD TC 및 buffer 관련 refactoring
  SSDProject/SSD/File.cpp
  SSDProject/SSD/SSD.cpp
Labels: Refactor

#107 Feature/rebuild refact
  SSDProject/Shell/Runner.cpp
  SSDProject/Shell/Runner.h
  SSDProject/Shell/ShellTestBuilder.cpp
  SSDProject/Shell/ShellTestBuilder.h
  SSDProject/Shell/shell.cpp
  SSDProject/Shell/shell.h
Labels: Refactor

#110 Feature/codingstandard_2
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD/main.cpp
  SSDProject/Shell/LoopWriteAndReadCompare.cpp
  SSDProject/Shell/Runner.cpp
  SSDProject/Shell/Runner.h
  SSDProject/Shell/SSDAdapter.cpp
  SSDProject/Shell/SSDAdapter.h
  SSDProject/Shell/ShellLogger.h
  SSDProject/Shell/testapp2.cpp
  SSDProject/Shell/write10andcompare.cpp
Labels: Style

#111 fix: fix compile error for cmdBuf naming
  SSDProject/SSD/SSD.cpp
Labels: fix

#113 [refactor] refactor file
  SSDProject/SSD/File.cpp
  SSDProject/SSD/SSD.cpp
Labels: Refactor

#112 Refactor : 카멜 표기법에 따라 SsdDriver --> ssdDriver 변경
  SSDProject/Shell/shell.cpp
  SSDProject/Shell/shell.h
Labels: Refactor

#116 [refactoring] extract lba check to function
  SSDProject/SSD/SSD.cpp
Labels: Refactor

#115 Feat : 사용 가능한 테스트 시나리오 목록을 출력하는 기능 추가
  SSDProject/Shell/LoopWriteAndReadCompare.cpp
  SSDProject/Shell/LoopWriteAndReadCompare.h
  SSDProject/Shell/Runner.cpp
  SSDProject/Shell/Runner.h
  SSDProject/Shell/ShellTestBuilder.cpp
  SSDProject/Shell/ShellTestBuilder.h
  SSDProject/Shell/TestCase.h
  SSDProject/Shell/main.cpp
  SSDProject/Shell/shell.cpp
  SSDProject/Shell/shell.h
  SSDProject/Shell/testapp1.cpp
  SSDProject/Shell/testapp1.h
  SSDProject/Shell/testapp2.cpp
  SSDProject/Shell/testapp2.h
  SSDProject/Shell/write10andcompare.cpp
  SSDProject/Shell/write10andcompare.h
Labels: Feat

#119 [refactoring] ssd flush count macro
  SSDProject/SSD/SSD.cpp
Labels: Refactor

#120 [feat] enable buffered write, erase
  SSDProject/SSD/main.cpp
Labels: Feat

#122 [fix] handle 2 argument in main
  SSDProject/SSD/main.cpp
Labels: fix

#121 Feat : main문에 argc, argv를 입력으로 받아서 shell.exe {command} 명령이 가능하도록 수정
  SSDProject/Shell/main.cpp
Labels: Feat

#124 Feat : flush 기능 추가
  SSDProject/Shell/SSDAdapter.cpp
  SSDProject/Shell/SSDAdapter.h
  SSDProject/Shell/SSDInterface.h
  SSDProject/Shell/main.cpp
  SSDProject/Shell/shell.cpp
  SSDProject/Shell/shell.h
  SSDProject/Shell_TC/test.cpp
Labels: Feat

#123 Refactor : showHelp() 함수 추가하여 코드 중복 방지
  SSDProject/Shell/main.cpp
Labels: Refactor

#125 fix: handle invalid argument
  SSDProject/SSD/main.cpp
Labels: fix

#126 [Feat] add buffer file
  SSDProject/SSD/File.cpp
  SSDProject/SSD/SSD.cpp
  SSDProject/SSD/main.cpp
  SSDProject/SSD_TC/test.cpp
  SSDProject/Shell/SSDAdapter.cpp
  SSDProject/Shell/SSDAdapter.h
  SSDProject/Shell/SSDInterface.h
  SSDProject/Shell/shell.cpp
  SSDProject/Shell/shell.h
  SSDProject/Shell_TC/test.cpp
Labels: Feat

#131 Fix : fullwrite, erase, erase_range 버그 수정
  SSDProject/Shell/main.cpp
Labels: fix

#130 [Feat] senario_list 입력시 사용 가능한 list 출력 되도록 구현, help 메세지에 scenario_lis…
  SSDProject/Shell/Runner.cpp
  SSDProject/Shell/main.cpp
  SSDProject/Shell/shell.cpp
  SSDProject/Shell_TC/test.cpp
Labels: Feat

#133 Update README.md
  README.md
Labels: documentation

#132 Fix : erase, erase_range 범위 수정
  SSDProject/Shell/main.cpp
Labels: fix

#135 Feat: enum 정의 c++로 이동
  SSDProject/Shell/ShellTestBuilder.cpp
  SSDProject/Shell/ShellTestBuilder.h
Labels: Feat

#134 Feat: 잘못된 test name 입력 시 에러메세지
  SSDProject/Shell/Runner.cpp
Labels: Feat

#136 Documentation: ppt 파일 업로드
  SSD Project _ Team AAA.pptx
Labels: documentation, Feat
